### PR TITLE
feat(fonts): add input output icons

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by FredLL-Avaiga — COMMENTED** [review]
it's not nice to change the class names :-(

**Review by FabienLelaquais — APPROVED** [review]
Same comment as Fred though.
Not only class name changes impact the code, but the underscore is really not CSS...
Anyways....

**Comment by ghost** [comment]
My bad. I reexported the set from icomoon and didn’t notice you made adjustments in the icon names generated by the tool.

As for "underscore is really not CSS" that’s debatable. I don’t like it either, most of the time, but some CSS conventions, such as BEM, use it pretty heavily so that’s more a matter of personal taste I guess.

**Review by FredLL-Avaiga — APPROVED** [review]

**Review by FabienLelaquais — APPROVED** [review]
👌

**Comment by ghost** [comment]
@FredLL-Avaiga @FabienLelaquais If it’s good for you, I let you merge this. I don’t have the right to do so myself on that repo.

**Pull request merged**
